### ISSUE TITLE
ValueError: arrays must all be same length

### ISSUE THREAD

**Issue by dc-aichara** [man-c/pycoingecko#8]
Dear Authors. 
Thank you for great library. I have been using `pycoingecko` for long time. 
I get an error while requesting for historical market data of a cryptocurrency by id, vs_currency and days.  

`pycoingecko` gives ValueError when days > 813, **But CoinGecko API V3 works fine**. 

See attached screenshots for your reference.  
<img width="1359" alt="Screen Shot 2019-06-24 at 11 04 21" src="https://user-images.githubusercontent.com/44660920/59986260-f9070080-9670-11e9-91e6-f3999443cab1.png">
<img width="1149" alt="Screen Shot 2019-06-24 at 11 04 46" src="https://user-images.githubusercontent.com/44660920/59986286-1b991980-9671-11e9-85e0-527d33847179.png">

**Comment by man-c** [comment]
Hello!
This is not an error by pycoingecko, but it comes from pandas. You can check it by running  `api.get_coin_market_chart_by_id('bitcoin','usd',2000)` without `pd.DataFrame`. The error raises because you are trying to create a DataFrame using arrays with different size.

More specific `api.get_coin_market_chart_by_id('bitcoin','usd',2000)` returns a dictionary with three arrays `['prices', 'market_caps', 'total_volumes']`, but their sizes are not equal (prices: 2000, market_caps: 1999, total_volumes: 2000). It seems that a value is missing from `market_caps` for Bitcoin. 

With a fast check it seems that CoinGecko is missing market_cap for Bitcoin on April 2, 2017 (timestamp: 1491091200000).

Best,
Manolis

**Comment by Endogen** [comment]
I would classify that as a CoinGecko bug and think that they fix it you you @dc-aichara report it. they have a pretty active Telegram channel if you want to do it in an easy way: https://t.me/coingecko

**Comment by dc-aichara** [comment]
@man-c   Thank you for your response. I am sorry. It was my mistake. I didn't check  length of arrays.  
@Endogen  I have reported bug to **CoinGecko**. 
Thank You. 🙏
